### ISSUE TITLE
Not possible to configure kernel

### ISSUE THREAD

**Issue by kolipka** [Samsung/TinyAra#7]
os/kernel/Kconfig loads:
```
comment "Kernel Latency utility"
source kernel/latency/Kconfig

comment "Kernel Debug and Simulation"
source kernel/debug/Kconfig

```
both folders are not existing. It is not possible to call `make menuconfig `

**Comment by sunghan-chang** [comment]
Hello kolipka.

Above codes were removed at commit dabbe21.

Thank you for notice.

Thanks
Sunghan
